-- ============================================================================
-- Part 3.5 — Sequences and Identity Columns
-- File: labs/sequences-identity-lab.sql
-- Classification: [LAB-ONLY — MUTATING — TRANSACTIONALLY CONTAINED]
-- Target: PostgreSQL 18
--
-- Run only in an authorized disposable, non-production database.
-- This script creates isolated objects and finishes with ROLLBACK.
-- It never calls nextval/setval on a pre-existing sequence.
-- Do not add COMMIT. Use a dedicated psql session.
-- ============================================================================

\set ON_ERROR_STOP on
\pset pager off

\echo 'Part 3.5 — Sequences and Identity Columns lab'

\if :{?lab_confirm}
\else
    \echo 'ERROR: explicit acknowledgement is required.'
    \echo 'Run with: -v lab_confirm=I_UNDERSTAND'
    \quit 3
\endif

SELECT :'lab_confirm' = 'I_UNDERSTAND' AS lab_confirmed \gset
\if :lab_confirmed
\else
    \echo 'ERROR: lab_confirm must equal I_UNDERSTAND.'
    \quit 3
\endif

SELECT
    current_database() AS database_name,
    current_user AS current_user,
    inet_server_addr() AS server_address,
    inet_server_port() AS server_port,
    pg_is_in_recovery() AS in_recovery;

SELECT to_regnamespace('tutorial_sequence_admin') IS NULL AS collision_free
\gset

\if :collision_free
    \echo 'Preflight passed: tutorial schema name is unused.'
\else
    \echo 'ERROR: tutorial_sequence_admin already exists.'
    \echo 'The lab will not reuse or remove an existing schema.'
    \quit 4
\endif

BEGIN;

SET LOCAL lock_timeout = '5s';
SET LOCAL statement_timeout = '2min';
SET LOCAL idle_in_transaction_session_timeout = '5min';

CREATE SCHEMA tutorial_sequence_admin;

CREATE SEQUENCE tutorial_sequence_admin.manual_id_seq
    AS bigint
    START WITH 100
    INCREMENT BY 1
    CACHE 1
    NO CYCLE;

CREATE TABLE tutorial_sequence_admin.always_example (
    id bigint GENERATED ALWAYS AS IDENTITY (
        START WITH 1
        INCREMENT BY 1
        CACHE 1
        NO CYCLE
    ),
    payload text NOT NULL,
    CONSTRAINT always_example_pk PRIMARY KEY (id)
);

CREATE TABLE tutorial_sequence_admin.default_example (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    payload text NOT NULL,
    CONSTRAINT default_example_pk PRIMARY KEY (id)
);

\echo 'Generate values and retrieve them with RETURNING'
INSERT INTO tutorial_sequence_admin.always_example (payload)
VALUES ('generated-always')
RETURNING id, payload;

INSERT INTO tutorial_sequence_admin.always_example (id, payload)
OVERRIDING SYSTEM VALUE
VALUES (5000, 'explicit-approved-override')
RETURNING id, payload;

INSERT INTO tutorial_sequence_admin.default_example (id, payload)
VALUES (7000, 'explicit-by-default')
RETURNING id, payload;

INSERT INTO tutorial_sequence_admin.default_example (payload)
VALUES ('generated-after-explicit')
RETURNING id AS generated_after_explicit
\gset

SELECT :generated_after_explicit = 1 AS by_default_sequence_not_advanced
\gset

\if :by_default_sequence_not_advanced
    \echo 'PASS: explicit BY DEFAULT value did not advance the identity sequence.'
\else
    \echo 'ERROR: expected the first generated BY DEFAULT identity to equal 1.'
    \quit 5
\endif

\echo 'Prove GENERATED ALWAYS rejects an ordinary explicit value'
DO $lab$
BEGIN
    BEGIN
        INSERT INTO tutorial_sequence_admin.always_example (id, payload)
        VALUES (6000, 'must-fail');
        RAISE EXCEPTION 'expected generated_always violation was not raised';
    EXCEPTION
        WHEN generated_always THEN
            RAISE NOTICE 'Expected generated_always violation observed';
    END;
END
$lab$;

\echo 'Sequence allocations survive savepoint rollback'
SELECT nextval('tutorial_sequence_admin.manual_id_seq') AS first_value
\gset

SAVEPOINT allocated_value_test;
SELECT nextval('tutorial_sequence_admin.manual_id_seq') AS rolled_back_value
\gset
ROLLBACK TO SAVEPOINT allocated_value_test;
RELEASE SAVEPOINT allocated_value_test;

SELECT nextval('tutorial_sequence_admin.manual_id_seq') AS value_after_rollback
\gset

SELECT
    :first_value = 100
    AND :rolled_back_value = 101
    AND :value_after_rollback = 102
        AS rollback_gap_confirmed
\gset

\if :rollback_gap_confirmed
    \echo 'PASS: observed 100, 101, rollback, then 102.'
\else
    \echo 'ERROR: sequence allocation did not match 100, 101, rollback, 102.'
    \quit 6
\endif

SELECT
    :first_value AS first_value,
    :rolled_back_value AS rolled_back_value,
    :value_after_rollback AS value_after_rollback;

SELECT currval('tutorial_sequence_admin.manual_id_seq') AS current_session_value;

\echo 'Inspect identity metadata'
SELECT
    table_schema,
    table_name,
    column_name,
    is_identity,
    identity_generation,
    identity_start,
    identity_increment,
    identity_cycle
FROM information_schema.columns
WHERE table_schema = 'tutorial_sequence_admin'
ORDER BY table_name, ordinal_position;

\echo 'Resolve associated identity sequences'
SELECT
    pg_get_serial_sequence(
        'tutorial_sequence_admin.always_example',
        'id'
    ) AS always_sequence,
    pg_get_serial_sequence(
        'tutorial_sequence_admin.default_example',
        'id'
    ) AS default_sequence;

\echo 'Inspect sequence configuration and observed state'
SELECT
    schemaname,
    sequencename,
    sequenceowner,
    data_type,
    start_value,
    min_value,
    max_value,
    increment_by,
    cycle,
    cache_size,
    last_value
FROM pg_sequences
WHERE schemaname = 'tutorial_sequence_admin'
ORDER BY sequencename;

\echo 'Inspect ownership dependencies'
SELECT
    seq_ns.nspname AS sequence_schema,
    seq.relname AS sequence_name,
    tbl_ns.nspname AS table_schema,
    tbl.relname AS table_name,
    att.attname AS column_name,
    dep.deptype
FROM pg_class AS seq
JOIN pg_namespace AS seq_ns
  ON seq_ns.oid = seq.relnamespace
LEFT JOIN pg_depend AS dep
  ON dep.classid = 'pg_class'::regclass
 AND dep.objid = seq.oid
 AND dep.refclassid = 'pg_class'::regclass
 AND dep.deptype IN ('a', 'i')
LEFT JOIN pg_class AS tbl
  ON tbl.oid = dep.refobjid
LEFT JOIN pg_namespace AS tbl_ns
  ON tbl_ns.oid = tbl.relnamespace
LEFT JOIN pg_attribute AS att
  ON att.attrelid = tbl.oid
 AND att.attnum = dep.refobjsubid
WHERE seq.relkind = 'S'
  AND seq_ns.nspname = 'tutorial_sequence_admin'
ORDER BY seq.relname;

\echo 'Show explicit BY DEFAULT value did not advance its sequence'
SELECT
    max(id) AS table_maximum,
    pg_get_serial_sequence(
        'tutorial_sequence_admin.default_example',
        'id'
    ) AS associated_sequence
FROM tutorial_sequence_admin.default_example;

ROLLBACK;

SELECT
    to_regnamespace('tutorial_sequence_admin') AS schema_after_rollback,
    to_regclass('tutorial_sequence_admin.manual_id_seq') AS sequence_after_rollback,
    to_regclass('tutorial_sequence_admin.always_example') AS table_after_rollback;

\echo 'LAB COMPLETE — all three final values must be NULL.'
