apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-headless
  namespace: elasticsearch-lab
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app: elasticsearch
  ports:
    - name: transport
      port: 9300
      targetPort: 9300
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: elasticsearch-lab
spec:
  selector:
    app: elasticsearch
  ports:
    - name: https
      port: 9200
      targetPort: 9200
